apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
  <match test>
    @type loki
    loki_url http://34.70.241.221:3100/loki/api/v1/push  <-- Replace with your URL
    labels namespace:logging,pod:test,container:test
</match>