apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-pos.log
      tag kubernetes.${container_name}
      <parse>
        @type none
      </parse>
    </source>

    <match kubernetes.**>
      @type loki
      url  http://13.232.201.254:3100/loki/api/v1/push  # Corrected parameter name
      <buffer>
        @type file
        path /var/log/fluentd-buffer
        flush_interval 1s
      </buffer>
    </match>