apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <match kubernetes.**>
    @type loki
    loki_url http://34.70.241.221:3100/loki/api/v1/push  # Update with your Loki address
    labels namespace: ${kubernetes.namespace}, pod: ${kubernetes.pod.name}, container: ${kubernetes.container.name}
   </match>
