---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: test
  labels:
    app: loki
spec:
  ports:
  - port: 3100
    targetPort: 3100
  selector:
    app: loki

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-config
  namespace: test
data:
  config.yaml: |  # Match the file name in args
    auth_enabled: false

    server:
      http_listen_port: 3100

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: inmemory
          replication_factor: 1
      chunk_idle_period: 5m
      chunk_block_size: 262144
      chunk_retain_period: 30s
      max_transfer_retries: 0

    schema_config:
      configs:
        - from: 2020-10-24
          store: boltdb
          object_store: filesystem
          schema: v11
          index:
            prefix: index_
            period: 168h

    storage_config:
      boltdb:
        directory: /tmp/loki/index

      filesystem:
        directory: /tmp/loki/chunks

    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h

    chunk_store_config:
      max_look_back_period: 0s

    table_manager:
      retention_deletes_enabled: false
      retention_period: 0s