apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: test
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:latest
        args:
          - -config.file=/etc/loki/config.yaml
        ports:
        - containerPort: 3100
        volumeMounts:
        - name: config
          mountPath: /etc/loki
        - name: wal-storage
          mountPath: /wal  # Ensure this path is writable
      volumes:
      - name: config
        configMap:
          name: loki-config
      - name: wal-storage
        persistentVolumeClaim:
          claimName: loki-wal-pvc  # Reference to the PVC
