apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  labels:
    app: loki
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:2.8.2
        args:
          - -config.file=/etc/loki/loki-config.yaml
        ports:
          - containerPort: 3100
        volumeMounts:
          - name: config-volume
            mountPath: /etc/loki
          - name: loki-storage
            mountPath: /var/loki
      volumes:
        - name: config-volume
          configMap:
            name: loki-config
        - name: loki-storage
          persistentVolumeClaim:
            claimName: loki-pvc
