apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-wal-pvc
  namespace: test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Adjust size as needed
