apiVersion: v1
kind: Service
metadata:
  name: testford-service
  namespace: test
spec:
  type: NodePort
  selector:
    app: testford
  ports:
    - port: 3000        # The port that the service will expose
      targetPort: 3000  # The port on the container that the service should forward to
      nodePort: 31111